---
- name: "Install required packages"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - gnupg2
    - curl

- name: "Install percona-release package"
  apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"

- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Set-up repo for MySql 8.0 version"
  shell:  percona-release setup ps80

- name: "Install Percona"
  apt:
    name: percona-server-server
    update_cache: yes
    state: latest
