---
- hosts: all
  become:
    true
  become_method:
    sudo
  roles:
        - install_Percona

- hosts: master
  become:
    true
  become_method:
    sudo
  roles:
        - master

- hosts: slave
  become:
    true
  become_method:
    sudo
  roles:
        - slave
